import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import mixpanel from "mixpanel-browser";

mixpanel.init('e2d303792fc362670118fa65dcaf2186', {
  autocapture: true,
  record_sessions_percent: 100,
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Magang Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
			<html
				lang="en"
				className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
				suppressHydrationWarning>
				<link rel="icon" href="/logo.svg" sizes="any" />
				<body className="min-h-full flex flex-col">{children}</body>
			</html>
		);
}
